// typescript/vue-ts-member/src/MemberRow.vue
<template>
    <tr>
        <td><img :src="member.avatar_url" alt=""></td>
        <td>{{ member.id }}</td>
        <td>{{ member.login }}</td>
    </tr>
</template>

<script setup lang="ts">
import { MemberEntity } from './model/MemberEntity';
// const props = defineProps({
//     member: {
//         type: Object,
//         default: {} as MemberEntity
//     }
// })
interface Props {
    member: MemberEntity
}
const props = defineProps<Props>()
</script>

<style lang="scss" scoped></style>

// react/member/src/components/MemberRow.tsx
import { MemberEntity } from "../model/member"
// props 类型约束
const MemberRow = ({ member }: { member: MemberEntity }) => {
  return (
    <tr key={member.id}>
      <td>
        <img src={member.avatar_url} style={{ maxWidth: '10rem' }} />
      </td>
      <td>{member.id}</td>
      <td>{member.login}</td>
    </tr>
  )
}
export default MemberRow
